[package]
name = "nydus-rafs"
version = "0.4.1"
description = "The RAFS filesystem format for Nydus Image Service"
authors = ["The Nydus Developers"]
license = "Apache-2.0 OR BSD-3-Clause"
homepage = "https://nydus.dev/"
repository = "https://github.com/dragonflyoss/nydus"
edition = "2024"
rust-version.workspace = true

[dependencies]
anyhow = "1.0.35"
arc-swap = "1.5"
bitflags = { version = "2.11.1", features = ["serde"] }
libc = "0.2"
log = "0.4"
nix = { version = "0.31.3", features = ["user"] }
serde = { version = "1.0.110", features = ["serde_derive", "rc"] }
serde_json = "1.0.53"
vm-memory = { workspace = true }
fuse-backend-rs = { workspace = true }
thiserror = "2.0.18"

nydus-api = { version = "0.5.0", path = "../api" }
nydus-storage = { version = "0.8.0", path = "../storage", features = [
    "backend-localfs",
] }
nydus-utils = { version = "0.6.0", path = "../utils" }

[dev-dependencies]
vmm-sys-util = { workspace = true }
assert_matches = "1.5.0"

[features]
fusedev = ["fuse-backend-rs/fusedev"]
virtio-fs = ["fuse-backend-rs/virtiofs", "vm-memory/backend-mmap"]
vhost-user-fs = ["fuse-backend-rs/vhost-user-fs"]

[package.metadata.docs.rs]
all-features = true
targets = [
    "x86_64-unknown-linux-gnu",
    "aarch64-unknown-linux-gnu",
    "aarch64-apple-darwin",
]
