[package]
name = "nydus-api"
version = "0.6.0"
description = "APIs for Nydus Image Service"
authors = ["The Nydus Developers"]
license = "Apache-2.0 OR BSD-3-Clause"
homepage = "https://nydus.dev/"
repository = "https://github.com/dragonflyoss/nydus"
edition = "2024"
rust-version.workspace = true

[dependencies]
libc = "0.2"
log = "0.4.8"
serde_json = "1.0.53"
serde_yaml = "0.9"
toml = "1.1.2"

thiserror = "2.0.18"
dbs-uhttp = { version = "0.3.0", optional = true }
http = { version = "1.4.0", optional = true }
mio = { version = "1.2", features = ["os-poll", "os-ext"], optional = true }
serde = { version = "1.0.110", features = ["rc", "serde_derive"] }
url = { version = "2.1.1", optional = true }

[dev-dependencies]
vmm-sys-util = { workspace = true }

[features]
handler = ["dbs-uhttp", "http", "mio", "url"]
